### ISSUE TITLE
ESPHome Password

### ISSUE THREAD

**Issue by Julius112** [mercenaruss/zigstar_gateways#1]
Hi Mercenaruss,

I really love your project and recently purchased one of your LAN Gateways. I've already added it to the Home Assistant Zigbee integration. However, to add it via the ESPHome integration I need to enter a password. What is the standard password of the pre-flashed Zigbee LAN Gateway? I couldn't find it anywhere in the docs.

Thanks a lot again for your great work.

Cheers,
Julius

**Comment by mercenaruss** [comment]
Hi, thank you very much for support, sorry for this small misunderstanding, I did a .yaml template and is available for download, this way you can input your own password and setting. [YAML](https://github.com/mercenaruss/zigstar_gateways/blob/main/files/ESP-HOME/zigstar-gw-lan.yaml), after you generate firmware you do upload it by accessing LAN Gateway IP and doing OTA Update.

**Comment by mercenaruss** [comment]
@Julius112 Firmware is update, you can download new .bin and upload using web interface and OTA.
Thank you for pointing this out.
![ZigStar LAN Gateway Update OTA](https://user-images.githubusercontent.com/5508130/131497958-695e9f92-be41-4813-b78a-d2ff64f1d003.png)

**Comment by Julius112** [comment]
Thanks a lot for your help!

Cheers,
Julius
