### ISSUE TITLE
Зависания WEB

### ISSUE THREAD

**Issue by lavrizone** [mercenaruss/zigstar_gateways#10]
Заметил зависания web части при активированной настройке MQTT, если остановить аддон Z2M, то вебморда шлюза очень плохо откликается на действия, страница обновляется раз в примерно 10 секунд, стоит Z2M запустить, то всё налаживается.

**Comment by mercenaruss** [comment]
@xyzroe Anything we can do about this?

**Comment by mercenaruss** [comment]
@xyzroe any idea about this?

**Comment by xyzroe** [comment]
I have no idea what is common between the mqtt configuration and the state of the z2m addon.  

Web interface freezes are possible if there is no connection with the mqtt server. This is how the mqtt library works which is used in the firmware.

If someone has the opportunity to make issue in the correct [repository](https://github.com/xyzroe/ZigStarGW-FW/issues), this will help not to forget about it, at the time of working on the firmware.
