### ISSUE TITLE
3.3V A short circuit     PCB problem C2 is incorrectly grounded in wiring and needs to be fixed. I also can't design the software, can't submit merge request

### ISSUE THREAD

**Issue by ahonxxx** [mercenaruss/zigstar_gateways#15]
![H~QUH8_O_GRGQ{W8D0G1IOL](https://user-images.githubusercontent.com/54906315/163800277-4410005e-cf4e-42ba-94e6-3a36fc0bd1fd.png)

**Comment by ahonxxx** [comment]
5V is also short-circuited
![A~D$DEF2NIYXYYJ4EH3V2S6](https://user-images.githubusercontent.com/54906315/163801503-19bafd99-3d99-4db4-8b75-4989f2e88155.png)

**Comment by mercenaruss** [comment]
Hi,let me check and update today.
Thank you for pointing out this issues,nobody reported till now.

**Comment by ahonxxx** [comment]
> 是否容易切断短路？我测试了还是不行，COM不能识别！

The copper sheet of the positive electrode of the capacitor needs to be cut off from top to bottom

**Comment by 65698888** [comment]
> 嗨，让我今天检查并更新。 感谢您指出这个问题，直到现在没有人报告。



> Hi,let me check and update today. Thank you for pointing out this issues,nobody reported till now.

Please inform  when updated, this is a very good project.

**Comment by mercenaruss** [comment]
@ahonxxx @65698888 Problem solved,updated Gerbers are available.
