### ISSUE TITLE
LilyZig: must 2.0mm UART be connected?

### ISSUE THREAD

**Issue by rea-ducks** [mercenaruss/zigstar_gateways#16]
Hi there,

does LilyZigs 6 pin 2.0mm UART need to be connected to the TTGO T-Internet-POE?
Because I'm lacking the right connector, I don't have it connected and the Multi Tool only gets timeouts. So I need to sort out if I just have to find the right connector or look for the error elsewhere.

**Comment by mercenaruss** [comment]
Hi,
yes,is required only for ESP firmware upload.
If you have USB-to-TTL then flash firmware for ESP and then everything else will be fine.
