### ISSUE TITLE
Wrong pin naming on the silk screen

### ISSUE THREAD

**Issue by rea-ducks** [mercenaruss/zigstar_gateways#19]
On the silk screen of the GW-TTGO-POE v1.2 pin 6 of the 16 pin connector to the TTGO is declared as "NC". But in fact it's connected to IO16 of the ESP and RES of the RF-Star. That's also how it's identified on the schematic.

**Comment by mercenaruss** [comment]
I will check and update silkscreen.

**Comment by mercenaruss** [comment]
@rea-ducks Gerbers updated. Thanks
