### ISSUE TITLE
Cannot connect to mqtt running as HA addon Client <unknown> disconnected, not authorised

### ISSUE THREAD

**Issue by evlo** [mercenaruss/zigstar_gateways#20]
I'm trying to have zigstar GW connect to mosquitto MQTT server running as HA addon (HA supervised) and getting these errors

```
2022-09-07 22:23:49: Client <unknown> disconnected, not authorised.
2022-09-07 22:24:34: New connection from on port 1883.
```

I tried these settings
(password is from home assistant integration where it says core-mosquitto etc.)
![image](https://user-images.githubusercontent.com/8813196/188970678-1703171a-1af7-4ccb-88ba-ab0b6b80fa05.png)

and also
![image](https://user-images.githubusercontent.com/8813196/188970972-61ca3f8b-d4bf-4189-89f2-15c7717adc74.png)

while having config like this
![image](https://user-images.githubusercontent.com/8813196/188970794-e11829b9-803f-4398-9a7f-13f6af6f8c2b.png)

zigbee2mqtt connects and communicates no problem whatsoever

https://github.com/mercenaruss/zigstar_gateways/issues/20

Any ideas why it does not connect?

**Comment by mmetzger1234** [comment]
Same issue, I  also noticed that the password field does not accept my entire long password on the mqtt config screen when i check the configMQTT.jason file. if i enter the full password in the config jason file . it seems to never want to try to connect.

**Comment by evlo** [comment]
> Same issue, I also noticed that the password field does not accept my entire long password on the mqtt config screen when i check the configMQTT.jason file. if i enter the full password in the config jason file . it seems to never want to try to connect.

It happened to me one time too, but on second attempt it seemed to take full password.

**Comment by mercenaruss** [comment]
@xyzroe any idea on this issue?

**Comment by mercenaruss** [comment]
@evlo all software related issues,can be discussed here: https://github.com/xyzroe/ZigStarGW-FW
