### ISSUE TITLE
Broken links in repository

### ISSUE THREAD

**Issue by letovlive** [mercenaruss/zigstar_gateways#23]
There are broken links on the website and its crosslinks after the last files rearrange.

**Comment by letovlive** [comment]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/8958129/195546765-165bb7d0-b9b4-469a-bc1e-984abb9aa2d9.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/8958129/195546915-0e0f7ef0-ffc7-4f1b-aaa3-50a309215347.png">

**Comment by letovlive** [comment]
the same 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/8958129/195547869-9689eef6-59d9-492c-aa40-d9295c659215.png">

I believe it is better to use some automated crawler to analyze broken links.

<img width="673" alt="image" src="https://user-images.githubusercontent.com/8958129/195548412-22112387-4c3a-48d5-8894-9c63b98021a7.png">

I've used integrity
https://apps.apple.com/us/app/integrity/id513610341?mt=12

**Comment by mercenaruss** [comment]
Issues fixed,thank you for pointing out.
Now checking all broken links for all locations.
