### ISSUE TITLE
Use the SMA antenna with Ebyte E72-2G4M20S1E issue

### ISSUE THREAD

**Issue by phoenixxie0** [mercenaruss/zigstar_gateways#25]
If we want to Use the SMA connector with Ebyte E72-2G4M20S1E to make the module.  To work with an external antenna, it must to cut the traces of the built-in antenna and solder the SMA connector directly to them. The built-in antenna is not intended to be used.
Like this pic
![image](https://user-images.githubusercontent.com/1797318/213925735-8cf503d2-d833-4962-b440-0688dc49b934.png)

**Comment by mercenaruss** [comment]
Correct,this is a default requirement.
