### ISSUE TITLE
The latest STL files can't be opened in prusaslicer

### ISSUE THREAD

**Issue by rrozema** [mercenaruss/zigstar_gateways#28]
An error code occurs when importing into latest PrusaSlicer (v2.5.2 on win64) the latest revisions of each of the zigstar stl files from the WT32-ETH01_LAN_Gateway folder. Previous revisions can successfully be opened and printed though.

**Comment by mercenaruss** [comment]
Will check and revert here.

**Comment by mercenaruss** [comment]
@rrozema unfortunately i dont have source files anymore.
