### ISSUE TITLE
ZigiHat i2c VCC issue on RPI3b

### ISSUE THREAD

**Issue by Buuhuu** [mercenaruss/zigstar_gateways#32]
Hey, I am using the ZigiHat on a Raspberry Pi 3 Model B rev 1.2 (not the b+ so without the PoE header) and I am trying to connect another extension board using the qwiic interface. For some reason the VCC on the i2c interface is only 2.3V (2.6V with the backup battery in place). I would expect it to be 3.3V as it is the case for the raspberry pi. The power supply of the raspberry pi itself seems stable and both 3.3V and 5V on the gpio header work as expected. It seems that the operation voltage of the whole board is only 2.3V which is in rage of what the RF module supports but also there 3.3V is recommended.

Am I doing something wrong? Is the ZigiHat only supported in RPI3b+/4 with the PoE header? 

Is there any "fix" I could apply to make it work on the RPI3b? I assume just connecting i2c VCC to 3.3V is not such a good idea.

Would you mind to share the schematics of the board?

**Comment by mercenaruss** [comment]
Replied to email about procedure.
