### ISSUE TITLE
Test and list ZigStar Gateway compatibility with Jeedom Official Zigbee Plugin (which is based on zigpy)

### ISSUE THREAD

**Issue by Hedda** [mercenaruss/zigstar_gateways#6]
Suggest you test and list ZigStar Gateway compatibility with Jeedom Official Zigbee Plugin (which is based on [zigpy](https://github.com/zigpy/zigpy) like [ZHA](https://www.home-assistant.io/integrations/zha)):

Jeedom Official Zigbee Plugin is based on [zigpy](https://github.com/zigpy/zigpy) (similar to the [ZHA integration component in Home Assistant](https://www.home-assistant.io/integrations/zha)) so should work:

https://blog.jeedom.com/5183-tout-ce-quil-faut-savoir-sur-le-plugin-officiel-zigbee/ <- Announcement is btw a great read!

https://market.jeedom.com/index.php?v=d&p=market_display&id=4050

https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/

"_The Zigbee plugin for Jeedom builds on the excellent work done around the open-source Zigpy library to offer general compatibility with different Zigbee hardware. It allows communication with the following Zigbee controllers_"

https://doc.jeedom.com/en_US/plugins/automation%20protocol/zigbee/changelog

https://community.jeedom.com/t/plugin-officiel-zigbee/58321

https://community.jeedom.com/t/plugin-zigbee-beta/40301

https://community.jeedom.com/t/plugin-zigbee-beta-blabla/53420

https://community.jeedom.com/tag/plugin-zigbee

https://compatibility.jeedom.com/index.php?v=d&p=home&search=&lang=en_US&protocol=Zigbee

Note that while the Jeedom Official Zigbee Plugin is open source but you need to buy it and install it to get the Python code for it.

Also note that the Jeedom Official Zigbee Plugin currently uses a fork of zigpy which already supports ZGP (Zigbee Green Power)

https://github.com/jeedom/zigpy

ZGP (Zigbee Green Power) has been submitted to upstream zigpy as a feature patch but that patch has not yet been merged yet.

Jeedom Logo

![image](https://user-images.githubusercontent.com/6320001/139655736-521a9ece-f1cd-438e-aaef-79f724bbb580.png)

PS: I have no affiliations with Jeedom myself in any way, as I am just a fan of the zigpy project and all SW/HW projects related to it.

**Comment by mercenaruss** [comment]
Jeedom list in their website and github,that they support all list of adapters from Z2M project.
Not necessary to list myself anywhere.
