### ISSUE TITLE
Test and list ZigStar Gateway compatibility with IoBroker Zigbee

### ISSUE THREAD

**Issue by Hedda** [mercenaruss/zigstar_gateways#8]
Suggest you test and list ZigStar Gateway compatibility with IoBroker Zigbee:

https://www.iobroker.net/

https://www.iobroker.net/#de/adapters/adapterref/iobroker.zigbee/README.md

Their website does not look like it has been updated but it does support cc26x2 and Z-Stack 3.x 

https://github.com/ioBroker/ioBroker.zigbee

IoBroker Zigbee is based on zigbee-herdsman (similar to Zigbee2MQTT):

https://github.com/Koenkk/zigbee-herdsman

So if works with Zigbee2MQTT it should also work with IoBroker Zigbee.

IoBroker logo for when listing compatibility:

https://commons.wikimedia.org/wiki/File:IoBroker_Logo.png

**Comment by mercenaruss** [comment]
IoBroker was tested by Russian & German community,it's working properly.
